controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    bumperbot_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

bumperbot_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint

